### ISSUE TITLE
fix(exp): add `PRPRC = 0` implies `WCP_FLAG = 0` and change WCP lookup selector

### ISSUE THREAD

**Issue by lorenzogentile404** [Consensys/linea-constraints#500]

**Comment by OlivierBBB** [comment]
This change is wrong. The issue is that `WCP_FLAG` belongs to the `PRPRC` perspective. Its values outside of that perspective may be arbitrary (outside of being binary.) Similarly the lookup requires the pre-selection with the `PRPRC` flag.
